### ISSUE TITLE
能搞成支持mysql么？

### ISSUE THREAD

**Issue by leogong** [wuyouzhuguli/FEBS#1]

**Comment by wuyouzhuguli** [comment]
有空会弄个MySQL版本

**Comment by leogong** [comment]
@wuyouzhuguli 好的，多谢，本地装oracle成本有点高

**Comment by eeve** [comment]
@leogong 可以暂时使用这个跑起来, 简单的改了下支持了MySQL. SQL文件在`sql/init.mysql.sql`

https://github.com/V2Git/FEBS/tree/mysql-support

**Comment by AAA-AA** [comment]
改造一下应该没问题

**Comment by wuyouzhuguli** [comment]
MySQL版本今天或明天就会发布

**Comment by wuyouzhuguli** [comment]
MySQL已上传到mysql分支。

**Comment by leogong** [comment]
真迅猛
