### ISSUE TITLE
用户权限BUG

### ISSUE THREAD

**Issue by pingyanzhang** [wuyouzhuguli/FEBS#16]
1、普通用户（smith）登录后，点击【网络资源->每日一文】
（PS：点击“每日一文”后，Shiro调用用户授权代码，并将该用户的授权链接存入缓存）
2、不点退出，地址栏输入登录页面/login.
3、然后再用管理员用户（mrbird）登录，登录后，那些需要授权才能访问的菜单链接，点击都会报 “{"msg":"暂无权限，请联系管理员！","code":500}”
5、同理，反过来的话。普通用户居然就可以访问管理员的才能访问的url了。

**Comment by wuyouzhuguli** [comment]
感谢指出，已修复。
