### ISSUE TITLE
弹窗先点开修改，再点开新建以后，某些输入框不可用

### ISSUE THREAD

**Issue by ZombieMisaka** [wuyouzhuguli/FEBS#3]
例子：  
用户管理页面，选中一个用户，点击修改用户，此时用户名和密码不能更改，关闭此页面，点击新增用户，此时用户名和密码仍然不能更改。

**Comment by wuyouzhuguli** [comment]
这个目前的设定就是这样的：
1. 用户创建后不可修改用户名；
2. 密码默认123456，用户可自己登录修改。

**Comment by ZombieMisaka** [comment]
不不，你没理解我的意思，先打开修改用户的时候，的确用户名是不可以改的，然后再打开新增用户页面的时候，username的readonly属性还是锁定的，所以新建用户无法输入用户名。

**Comment by wuyouzhuguli** [comment]
soga，明天修正下，感谢！

**Comment by wuyouzhuguli** [comment]
已修复，再次感谢指正。
